version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250" # Model protocol for Collector to talk to Jaeger

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/config/otel-config.yaml"]
    volumes:
      - ./config/otel-config.yaml:/config/otel-config.yaml
    ports:
      - "4317:4317" # gRPC Receiver
      - "4318:4318" # HTTP Receiver