global:
  resolve_timeout: 5m

route:
  receiver: webhook-test
  group_by: [ "alertname", "job" ]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h

receivers:
- name: webhook-test
  webhook_configs:
  - url: "<your_webbhok_url_here>" # Replace this in the next step
    send_resolved: true
