receivers:
  filelog:
    include:
    - '/Library/Containers/com.docker.docker/Data/log/*.log'
    start_at: end
    storage: file_storage
    user: 0

extensions:
  file_storage:
    directory: /etc/otelcol-contrib/.data/storage/
    create_directory: true

exporters:
  file:
    path: /etc/otelcol-contrib/.data/output_logs.log

service:
  extensions: [ file_storage ]
  pipelines:
    logs:
      receivers: [ filelog ]
      processors: []
      exporters: [ file ]
