receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:


exporters:
  # Export Traces to Jaeger
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      # FIX: Must be TRUE for local docker setup
      insecure: true

  # Export Metrics to Prometheus
  prometheus:
    # This creates a scrape endpoint at http://otel-collector:8889/metrics
    endpoint: "0.0.0.0:8889"
    namespace: "my_node_service" # Optional: adds a prefix to metrics

  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/jaeger, debug ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus, debug ]
