#Vesrion # 1
# global:
#   scrape_interval: 5s # Scrape often for this demo

# scrape_configs:
# - job_name: 'otel-collector'
#   static_configs:
#   - targets: [ 'otel-collector:8889' ] # Prometheus scrapes the Collector

# Version # 2

global:
  scrape_interval: 5s

scrape_configs:
- job_name: 'otel-collector'
  static_configs:
  - targets: [ 'otel-collector:8889' ]
